Pin jetty versions (#68)
- Unpinned versions caused ewer versions to be pulled in that in turn made jakarta.servlet-api (the successor of javax.servlet-api) required for compilation, causing the exception `java.lang.NoClassDefFoundError: jakarta/servlet/ServletContextListener` on start-up.